name: tests unitaires
on: [push]
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python for Demo
        uses: actions/setup-python@v6
      - name: Run tests
        run: pytest TP1/test.py
